CREATE TABLE IF NOT EXISTS orp_singleton (
  name VARCHAR(64) NOT NULL PRIMARY KEY,
  document JSON NOT NULL,
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
