CREATE TABLE IF NOT EXISTS orp_log_event (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  event_key CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  kafka_topic VARCHAR(249) NOT NULL,
  kafka_partition INT NOT NULL,
  kafka_offset BIGINT NOT NULL,
  node_id BIGINT NULL,
  node_name VARCHAR(128) NOT NULL,
  log_type VARCHAR(32) NOT NULL,
  resource_kind VARCHAR(16) NOT NULL DEFAULT '',
  resource_id BIGINT NULL,
  event_ts DATETIME(6) NOT NULL,
  status SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  response_time DOUBLE NOT NULL DEFAULT 0,
  host VARCHAR(255) NOT NULL DEFAULT '',
  remote_addr VARCHAR(64) NOT NULL DEFAULT '',
  request_uri TEXT NOT NULL,
  bytes_sent BIGINT NOT NULL DEFAULT 0,
  request_bytes BIGINT NOT NULL DEFAULT 0,
  message MEDIUMTEXT NOT NULL,
  received_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  UNIQUE KEY uq_orp_log_kafka_offset (kafka_topic, kafka_partition, kafka_offset),
  KEY idx_orp_log_node_type_time (node_id, log_type, event_ts),
  KEY idx_orp_log_resource_type_time (resource_id, log_type, event_ts),
  KEY idx_orp_log_name_type_time (node_name, log_type, event_ts),
  KEY idx_orp_log_event_time (event_ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
